### ISSUE TITLE
Replicating results in README.md

### ISSUE THREAD

**Issue by dazzler2** [kylebutts/did2s_stata#16]
Hi - I tried replicating the event study results in README.md after downloading the df_het.dta file. The coefficients are the same as those shown in the README file. However, the standard errors are different. Also, the standard error for rel_year_shift = 0 cannot be estimated. (See output below.) Is this a problem with the ado file, or does the example in the README file simply not reflect recent updates? Also, is there a reason why the standard error for the first event time indicator cannot be estimated? Thanks!

![image](https://github.com/user-attachments/assets/daa5800b-316a-4626-9c15-e846e690f655)

**Comment by kylebutts** [comment]
Thanks, fixed.
