### ISSUE TITLE
Period Names in e(b) / e(V)

### ISSUE THREAD

**Issue by Crossfade14** [kylebutts/did2s_stata#6]
Hi, thank you very much for the very nice package!

I just realised a minor thing for future improvements: 
The estimation/CI results stored in e(b)/e(V) are all linked to the name of the treatment variable (lets say "rel_year"). So when you for example try to plot the estimates with coefplot the x-axis only shows "rel_year" for every entry instead of the actual period. Other methods (e.g. did_imputation, csdid, did_multiplegt, xtreg etc) directly store the relative names of the period, which renders it a lot easier to use coefplot or even better event_plot afterwards. Especially for the latter one I could not find a way to get it working yet (but I am rather a beginner to be honest. Probably one could manually adjust every single period name per matrix operators?).

Of course this could at leat for coefplot be adjusted manually within the coefplot options, yet maybe this is something you might want to further improve the package on.

Anyway thanks a lot for the great work so far!

**Comment by kylebutts** [comment]
Hi there,

The problem is that i. in stata does not allow negative values, so I have to shift the rel_year. You can manually unshift with postestimation commands :-)
