### ISSUE TITLE
Typos in help file

### ISSUE THREAD

**Issue by brachchampion** [kylebutts/did2s_stata#9]
There are inconsistencies in the syntax help. The option names are different in the Syntax description and option descriptions (e.g. treat_formula vs second-stage). Also a typo in the description of treatment(varname): "(shift D_it the *number* of periods of anticipation)."

Overall I am happy with the package. It was served fresh and tasted delicious. My waiter was very gracious when I texted him a bazillion questions. I would give five stars but I hate staggered diff-in-diff models, 4.5 stars.

**Comment by kylebutts** [comment]
Fixed it: d9f34b0b588703cbeac70afcb59b63a446def5e7 and 0ee223068d57e9dec668d85b8ac5aa23efd2491b
